version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/pathfinding-vue"
    schedule:
      interval: "weekly"
  - package-ecosystem: "nuget"
    directory: "/pathfinding"
    schedule:
      interval: "weekly"
