version: "3.9"
services:
  vue:
    build: 
      context: ./vue
    ports: 
      - target: 80
        published: 8000
  api:
    build:
      context: ./api
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - target: 80
        published: 8001