version: "3.9"
services:
  vue-app:
    build: 
      context: ./pathfinding-vue
    ports: 
      - target: 80
        published: 3000

  pathfinding-api:
    build:
      context: ./pathfinding-api
    environment: 
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - target: 80
        published: 3001