name: Build docker images
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build vue-app
      run: docker-compose build vue-app
    - name: Build backend-app
      run: docker-compose build backend-app