name: Build docker images
on:
  pull_request:
    branches: [ master ]
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build vue-app
      run: docker-compose build vue-app
    - name: Build pathfinding-api
      run: docker-compose build pathfinding-api