name: Build docker images
on:
  pull_request:
    branches: [ master ]
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build vue
      run: docker-compose build vue
    - name: Build api
      run: docker-compose build api
