name: node.js test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  run-test:

    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./pathfinding-vue

    strategy:
      matrix:
        node-version: [12.x, 14.x, 15.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install dependencies
      run: npm ci
    - name: Build
      run: npm run build
    - name: Test
      run: npm run test
